version: 2.1
jobs:
  lint212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u212_1.2.8_2.12.9
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.9! check
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  lint212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.3_1.2.8_2.12.9
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.9! check
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u212_1.2.8_2.12.9
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.9! test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.3_1.2.8_2.12.9
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.9! test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  release:
    docker:
      - image: hseeberger/scala-sbt:8u212_1.2.8_2.12.9
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: sbt-cache
      - run: echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$SONATYPE_USER\", \"$SONATYPE_PASSWORD\")" > ~/.sbt/1.0/sonatype.sbt
      - run: echo -n "${PGP_PUBLIC}" | base64 -d > /tmp/public.asc
      - run: echo -n "${PGP_SECRET}" | base64 -d > /tmp/secret.asc
      - run: ./sbt ++${SCALA_VERSION}! clean sonatypeBundleClean publishSigned sonatypeBundleRelease

workflows:
  version: 2
  build:
    jobs:
      - lint212_jdk8:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - lint212_jdk11:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - test212_jdk8:
          requires:
            - lint212_jdk8
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - test212_jdk11:
          requires:
            - lint212_jdk11
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - release:
          context: Sonatype
          requires:
            - test212_jdk8
            - test212_jdk11
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
